package com.android.myscraper.domain.model.api.modules;

public enum Proxy {
    ETH_BLOCKNUMBER, ETH_GETBLOCKBYNUMBER, ETH_GETBLOCKTRANSACTIONCOUNTBYNUMBER, ETH_GETTRANSACTIONBYBLOCKNUMBERANDINDEX, ETH_GETTRANSACTIONCOUNT, ETH_SENDRAWTRANSACTION,
    ETH_CALL, ETH_GETCODE, ETH_GETSTORAGEAT, ETH_GASPRICE, ETH_ESTIMATEGAS;
}
